version: '3'
services:
  youtube:
    image: ryanvanmass/youtube-dl:v2.1
    container_name: youtube-dl
    volumes:
      - /media:/home/youtube/output:rw
    
    # Enter Youtube URL here
    command: 