version: '3'
services:
  upodder:
    image: ryanvanmass/upodder:v2
    container_name: upodder
    volumes:
      - /media:/home/youtube/output:rw
    
    command: cat ${URL} >> /root/.upodder/subscriptions && upodder